  
spring:
  datasource:
    password: root
    username: root
    url: 'jdbc:mysql://localhost:8806/loja'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
